### PR TITLE
Add initial pep8 support.

### PR DESCRIPTION
**Pull request by sontek**
This ignores plenty of warnings and errors in pep8 and only
focuses on a small subset that can easily be achieved.

Ignores applying pep8 to tests for now and only enforces on
the pyramid core code.

### CODE REVIEW

**Comment by sontek** [comment]
The big difference between this and #1339 is that it enables pep8 in tox.ini and doesn't run pep8 on setup.py or tests currently.  This allows us to slowly adopt pep8 and catch errors as they are introduced.

**Comment by mmerickel** [comment]
2 whitelines between top-level objects has always been uncomfortable to me.

**Comment by sontek** [comment]
@mmerickel Yeah, I disabled that one but I had made a couple of those changes out of habit

**Comment by sontek** [comment]
@mmerickel Looks like I did it 6 times ;)  More of a habit than I thought.   I'll go remove those changes

**Comment by mmerickel** [comment]
I think we can add this to 1.6, however it's gonna have to go in after the other pending PRs then we'll update this to avoid any merge conflicts.

**Comment by marioidival** [comment]
https://github.com/Pylons/pyramid/pull/1339

**Comment by sontek** [comment]
@mmerickel I've resolved the conflicts for this one, are there many PRs coming in before we merge this?

**Comment by mmerickel** [comment]
I'm waiting on #1557 and #1568, but that's it!

**Comment by sontek** [comment]
@mmerickel they've all been merged ;) ;)

**Comment by bertjwregeer** [comment]
@sontek with the pep8 merge ;-)

**Comment by mmerickel** [comment]
This is merged. I think we will not apply this to 1.x-branch to avoid screwing with their history too much.

**Pull request merged**
