### PR TITLE
Overhaul Style Guide

### PR DESCRIPTION
**Pull request by stevepiercy**
This PR addresses issue #2633, and expands the Style Guide as an easy reference for documentation authors.

Request review and feedback.

### CODE REVIEW

**Comment by bertjwregeer** [comment]
I feel that `Typographical Conventions` should stick around. That document is not for the authors of the documentation, it exists for the users of the documentation, especially those that use it in PDF form.

The `Style Guide` documentation has a very different audience from the one for a typical `Typographical Conventions` document.

**Comment by stevepiercy** [comment]
@bertjwregeer Typo Conv is back and better than ever.

One day, when we have a useful pylonsproject.org, I'll move the Style Guide over there to share across all Pylons Project projects.

**Comment by stevepiercy** [comment]
We're close to releasing the new pylonsproject.org. However, I want to use Sphinx to render `style-guide.rst` because it is for docs and uses Sphinx markup, so it makes sense to have it here and rendered.

If there are no further suggestions or objections, then I'll merge this PR this evening.

**Comment by bertjwregeer** [comment]
There are things in the Typographical Conventions that don't belong there.

Such as what a bulleted list is, or headings. It needs to contain a little information for users to know "Ah, that means it's code" or "that is a command I run" or "this is a warning".

Here's some typographical conventions from three random books I pulled down off my bookshelf:

For Dummies:
fullsizerender 3

Cisco Press:
fullsizerender 2

O'Reilly:
fullsizerender 4

**Comment by stevepiercy** [comment]
@bertjwregeer Updated. I'll merge this evening if there are no further suggestions.

**Comment by bertjwregeer** [comment]
:+1: much better. Thanks!

**Comment by stevepiercy** [comment]
Thanks for the feedback!

**Pull request merged**
