### PR TITLE
alchemy: change file structure to modules for views and models

### PR DESCRIPTION
**Pull request by ergo**

### CODE REVIEW

**Comment by stevepiercy** [comment]
Please merge master back into this branch

**Comment by tseaver** [comment]
@stevepiercy you merged this PR with tests failing, and without any discussion.  I'm going to revert for now.

**Comment by tseaver** [comment]
@ergo Can you please get the tests passing (maybe submit a new PR and see what breaks on Travis)?

**Comment by stevepiercy** [comment]
Sorry, my bad, we didn't bring that conversation in from IRC. @ergo, would you please include an explanation for the merge?

**Comment by ergo** [comment]
@tseaver I probably need to make a new branch and then merge the 9 commits from this branch onto it, since this branch was 261 commits behind master, I'd like to preserve history but my git foo is weak.

**Pull request merged**
