### PR TITLE
Update authorization.rst

### PR DESCRIPTION
**Pull request by areski**
fix the url for hello route '/howdy'

### CODE REVIEW

**Comment by tseaver** [comment]
[`howdy` is not the view name](https://github.com/Pylons/pyramid/blob/e564ff8aa47aed237d7c148056260fb89d781004/docs/quick_tutorial/authorization/tutorial/views.py#L26).

**Comment by areski** [comment]
As the name is starting by a '/' I wasn't sure we refer to the name of the route but rather the url, '/howdy' is the correct url
https://github.com/Pylons/pyramid/blob/e564ff8aa47aed237d7c148056260fb89d781004/docs/quick_tutorial/authorization/tutorial/__init__.py#L22

**Comment by tseaver** [comment]
My bad.

**Comment by tseaver** [comment]
(Or maybe Paul's bad for using a different view / route name than the actual URL name).

**Comment by areski** [comment]
nobody fault to my opinion, but it would have been cleaner to use hello everywhere

**Comment by pauleveritt** [comment]
It’s my style to have the URLs and routes and views have some differences, just to show there isn’t magic in naming.

—Paul

**Comment by tseaver** [comment]
My comment was actually in jest -- having them differ is reasonable.

**Pull request merged**
