### PR TITLE
Adding HTTP client error 418.

### PR DESCRIPTION
**Pull request by jenstroeger**
I would have liked to submit this PR on 1. April, but alas… ☺️

### CODE REVIEW

**Comment by bertjwregeer** [comment]
https://tools.ietf.org/html/rfc2324#section-2.3.2 specifies that the body if provided should be: "short and stout"

> Any attempt to brew coffee with a teapot should result in the error
>   code "418 I'm a teapot". The resulting entity body MAY be short and
>   stout.

Other than that this PR looks good.

**Comment by bertjwregeer** [comment]
@jenstroeger could you add yourself to `CONTRIBUTORS.txt` please, unless I somehow missed you in there.

**Comment by jenstroeger** [comment]
@bertjwregeer done.

**Comment by bertjwregeer** [comment]
Thank you!

**Comment by bertjwregeer** [comment]
It'll be a good April fools this year :P

**Comment by jenstroeger** [comment]
Indeed so, thank you @bertjwregeer!

**Pull request merged**
