### PR TITLE
Note's link is dead

### PR DESCRIPTION
**Pull request by Slevender**
The link in note does not give an expected result.

I also would like to thank everyone who have contributed to this amazing tutorial. Having a blast learning!

### CODE REVIEW

**Comment by stevepiercy** [comment]
@mcdonc @pauleveritt or @tseaver http://bfg.repoze.org/videos is dead. Is there a new URL for the videos, or are they lost forever?

@Slevender the .rst syntax in this PR is bad. Make sure you can build the docs locally before submitting a PR.

**Comment by Slevender** [comment]
@stevepiercy Okay. Sorry. I'm new to this stuff. Will try to be more careful next time.

**Comment by bertjwregeer** [comment]
There are no changes in this PR, should this to be a ticket instead?

**Comment by mmerickel** [comment]
The link and reference simply needs to be removed. I'm unaware of an alternate location of this content we could link to.

**Comment by stevepiercy** [comment]
@Slevender no problem. For instructions on how to build the docs, see https://github.com/Pylons/pyramid/blob/master/HACKING.txt

@bertjwregeer there is a `!` which causes the docs not to build.

**Comment by bertjwregeer** [comment]
@stevepiercy He added another commit that reverts that addition of a !. This makes this PR a no-op. Hence my question as to wether this would be better as a standard ticket and not a PR.

**Comment by tseaver** [comment]
We took down `bfg.repoze.org` because it was attracting abuse.  The videos are actually hosted at:

  http://static.repoze.org/casts/videotags.html

**Comment by stevepiercy** [comment]
I'll take this on tonight.

**Comment by stevepiercy** [comment]
@tseaver I could only get the second video to play in Chrome. I didn't try other browsers.

**Pull request closed without merging**
