### PR TITLE
deprecate pserve --daemon

### PR DESCRIPTION
**Pull request by mmerickel**
This should fix the following issues: #912, #1216, and #1554.

### CODE REVIEW

**Comment by mmerickel** [comment]
@bertjwregeer or @mcdonc can you weigh in on how I should go about deprecating this? I think the PR currently annotates the proper spots in the code for each possible subcommand, but I'm not sure dumping the warnings to stdout is best?

Anyway some feedback and I can fix the tests and merge it.

**Comment by mcdonc** [comment]
I'd probably use warnings.warn instead of dumping to stdout.  One way to do this if each switch ends up calling a method is to use ```zope.deprecation.deprecate``` as a decorator of that method:

```
@deprecate('This is a deprecated method...')
def themethod(self, foo):
    ....
```

**Comment by mmerickel** [comment]
I didn't go with `warnings.warn` because the CLI already outputs some stuff and after python 2.6 no one ever sees the warnings. The only way to turn on Python's deprecation warnings is to not use pserve, and use the module syntax.

```
$ env/bin/python -Wall -m pyramid.scripts.pserve development.ini --status
/Users/michael/work/oss/pyramid/pyramid/scripts/pserve.py:622: DeprecationWarning: The daemon options have been deprecated in Pyramid 1.6. They will be removed
in a future release per Pyramid's deprecation policy. Please consider using
a real process manager for handling your processes like supervisord or systemd.

The following commands are deprecated:
    [start,stop,restart,status] --daemon, --stop-server, --status, --pid-file

  ''', DeprecationWarning, stacklevel=1)
No PID file pyramid.pid
```

Also this is a deprecation of the CLI flags, not a misuse of a python function, so the stacklevel doesn't make as much sense either.

**Comment by mmerickel** [comment]
To be clear, python's `DeprecationWarning` support really is terrible now that they are turned off by default and I wish we used something else like `UserWarning`.

**Comment by mcdonc** [comment]
Yeah, I suppose since the command already dumps to stdout in this context it's fine to use print statements.

**Pull request merged**
