### PR TITLE
Docs style guide

### PR DESCRIPTION
**Pull request by stevepiercy**
See #2880.

DO NOT MERGE.

For ease of viewing, visit the rendered docs at:
https://docs.pylonsproject.org/projects/docs-style-guide/

This PR is intended only for review, discussion, and gain exposure for what will become a new, separate project.

## Todos
- [x] Update https://pylonsproject.org/community-how-to-contribute.html with a new sentence at the end of the first paragraph: "Documentation contributions should follow the [Pylons Project Documentation Style Guide](https://docs.pylonsproject.org/projects/docs-style-guide/)."
- [x] Update https://pylonsproject.org/community-coding-style-standards.html with "Documentation Style Guide" heading and text: "Documentation contributions should follow the [Pylons Project Documentation Style Guide](https://docs.pylonsproject.org/projects/docs-style-guide/)."
- [x] Update first sentence in Pyramid's and docs-style-guide's [contributing.md](https://github.com/Pylons/pyramid/blob/master/contributing.md) with "How to Contribute, Coding Style and Standards, and [Pylons Project Documentation Style Guide](https://docs.pylonsproject.org/projects/docs-style-guide/).
- [x] Add issue templates to Pyramid, using those from [docs-style-guide](https://github.com/Pylons/docs-style-guide/tree/master/.github/ISSUE_TEMPLATE) as examples.

### CODE REVIEW

**Comment by mmerickel** [comment]
I don't really agree with some of the strict rules like one sentence per line, or extra spaces after lists to keep them lined up (`#.  ` and `*   `) but it's fine, I can deal with it.

**Comment by stevepiercy** [comment]
Thanks for being flexible.

Technically the spacing/indent for lists is not necessary in reST. Its purpose is to make text editors work for the writer. For example, in the case of a list item that consists of multiple lines, sentences, or paragraphs, it makes indentation of subsequent lines consistent to four spaces. When indentation is inconsistent, it forces the writer to perform manual indentation corrections in text editors (PyCharm is especially fickle). It's even worse when there are a mix of bullet (2 columns) and numeric (3 columns) and definition lists.

For lines, I tried one paragraph per line, but that meant lots of horizontal scrolling on web-based tools, like diff in GitHub. That was awful. It's worse for GitHub diff when we use 79-character columns and have to rewrap paragraphs. I think we all agreed that semantic line breaks was a terrible idea (sorry, Plone). One sentence per line is not perfect either, but I feel it's the lesser of four evils.

All that said, these are "should" or "recommended", not "must" or "strictly". IOW, I might ask contributors to follow these points in the guide, but I won't require them to do so. Ultimately it's more important to keep and bring in people to write more and better docs.

**Comment by mmerickel** [comment]
Sure, the issue with using these rules with contributors is that the back and forth of several reviews is very discouraging - we want to minimize that as much as possible. Maybe look into an issue template or something with a link to the contributors guide and style guide if we can't come up with a way to enforce the style guide through automation.

**Comment by mmerickel** [comment]
Are you still planning to merge this into pyramid or is this just a test branch because it'll get better feedback here? Just trying to understand the purpose of this PR.

**Comment by stevepiercy** [comment]
This PR is only for discussion purposes, not to be merged. That has not changed. I hope more people chime in.

Ultimately I will move the content over to the `docs-style-guide` repo. It's new and has zero exposure.

**Comment by stevepiercy** [comment]
Closing in favor of #3362

**Pull request closed without merging**
