### PR TITLE
Feature: JSON exceptions

### PR DESCRIPTION
**Pull request by bertjwregeer**
This is to bring Pyramid in-line with the changes that were made to WebOb's exceptions and to allow for generation of JSON exceptions.

https://github.com/Pylons/pyramid/issues/2406

### CODE REVIEW

**Comment by bertjwregeer** [comment]
@mmerickel Take a look at this.

To understand why I was concerned WebOb was broken (and IMHO the ordering is wrong, but nobody but Apache implements it, and Apache implements it the same way as WebOb...) see this long issue: https://github.com/Pylons/webob/issues/239

Either way, this is ready to be merged as soon as tests come back satisfactory.

**Comment by mmerickel** [comment]
This looks great. Could you please add a changelog that mentions any possible incompatibilities?

**Comment by bertjwregeer** [comment]
Should be no incompatibilities. It now does the right thing when the client provides an `Acccept` of `application/json` and returns a JSON response.

I can add a CHANGELOG announcing the change.

**Comment by bertjwregeer** [comment]
I did match the signature for `json_formatter` to be the same as the one used by WebOb. This should allow users to easily move those between projects.

**Pull request merged**
