### PR TITLE
Minor comment fix

### PR DESCRIPTION
**Pull request by lkuchenb**

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
Thank you!

**Comment by stevepiercy** [comment]
The docs builds fail due to [Sphinx 4.0 deprecating repoze.sphinx.autointerface](https://github.com/repoze/repoze.sphinx.autointerface/issues/16) and can be ignored for now.

Lint also needs to be run, either in this PR or a separate one.

**Comment by lkuchenb** [comment]
@stevepiercy Fixed the linting issues

**Comment by stevepiercy** [comment]
@mmerickel @bertjwregeer I'm OK with merging this PR. Should we temporarily pin Sphinx to < 4.0?

**Pull request merged**
