### PR TITLE
Fix Sphinx 3.0.x build

### PR DESCRIPTION
**Pull request by stevepiercy**
WIP

Regarding these two warnings:

```
src/pyramid/request.py:docstring of pyramid.request.Request.response:1: WARNING: duplicate object description of pyramid.request.Request.response, other instance in api/request, use :noindex: for one of them
src/pyramid/request.py:docstring of pyramid.request.Request.session:1: WARNING: duplicate object description of pyramid.request.Request.session, other instance in api/request, use :noindex: for one of them
```

If I follow the advice do this:

```rst
   .. attribute:: response
     :noindex:
```

...then it does not have an index entry and cannot be linked to, like so:
https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.response

I see that further down the rendered page, another `response` and `session` appear, which are from the `request` docstrings.

I went ahead and tried a "fix" in commit , but I want to make sure that this doesn't mess up anything.

Alternatively, we could move all that rst into the docstrings, but I assume y'all put it at the top of the .rst file for a good reason.

### CODE REVIEW

**Comment by stevepiercy** [comment]
Blocked by https://github.com/sphinx-doc/sphinx/issues/7418#issuecomment-618869311

I do not want to replace all terms to the same word casing.

**Comment by stevepiercy** [comment]
I got a quick response from the Sphinx folks. I put the `suppress_warnings` option into tox instead of the `conf.py` because I prefer not to have that setting as a default when using Sphinx's `make foo`.

**Comment by stevepiercy** [comment]
Sphinx 3.0.x struck in Deform today. See my comment for further discussion about resolving duplicate entries: https://github.com/Pylons/deform/pull/397#pullrequestreview-401514094

**Comment by bertjwregeer** [comment]
I'm good with these changes.

**Pull request merged**
