### PR TITLE
Pdf rendering fixes

### PR DESCRIPTION
**Pull request by mcdonc**
This makes "tox -e pdf" work again on my machine.

### CODE REVIEW

**Comment by mcdonc** [comment]
Sup Steve.  :)

**Comment by russellballestrini** [comment]
Woah, it's a wild @mcdonc !

**Comment by bertjwregeer** [comment]
Hot damn...

**Comment by mmerickel** [comment]
huh, stupid rtd builds stuff with warnings as not errors and we don't have CI enabled for the pdfs

https://readthedocs.org/projects/pyramid/builds/7092052/

**Comment by bertjwregeer** [comment]
@mcdonc could you please squash the commits down to a single one so there aren't a bunch of merges?

**Comment by bertjwregeer** [comment]
@mmerickel PDF building on Travis didn't work right IIRC. Or at least there was a reason for it being disabled.

**Comment by stevepiercy** [comment]
@mmerickel @bertjwregeer here's the situation from about 2 years ago: https://github.com/Pylons/pyramid/issues/2575#issuecomment-219318783

It would be good to see if that is still the case. How would we do so?

**Comment by stevepiercy** [comment]
Sup Chris https://www.youtube.com/watch?v=NsJLhRGPv-M

**Comment by stevepiercy** [comment]
I hope to resolve [this issue with Unicode characters](https://github.com/Pylons/pyramid/issues/2572). I'm trying out a few things.

**Comment by stevepiercy** [comment]
I got it. If anyone would like to check it out, see https://github.com/Pylons/pyramid/issues/2572#issuecomment-384127786

**Comment by stevepiercy** [comment]
ping @mcdonc. Would you please:
* squash commits per @bertjwregeer's request
* remove the Sphinx todo extension and its configuration stanzas from `conf.py`
* Is there a reason to retain the latex stuff that you commented?

I'd like to merge this so that I can easily push out a fix for #2572 without dealing with merge conflicts. Thank you!

**Comment by mcdonc** [comment]
Not gonna squash cuz the merge commits happened over a 2 yr period but I'll take a look at the other stuff.

**Comment by bertjwregeer** [comment]
@mcdonc since the merges are just merging master in, if you squash it down to just a PR against current master, it'll be nicer. You might even be able to grab a git patch against master, and use that.

**Comment by mmerickel** [comment]
@mcdonc poke

**Comment by bertjwregeer** [comment]
```
git fetch --all
git rebase -i origin/master
<esc>:wq
git push -f
```

And it's done.

**Comment by mmerickel** [comment]
@stevepiercy if you still have issues you want fixed please make the changes yourself.

Thanks for fixing pdfs @mcdonc !

**Pull request merged**
