### PR TITLE
Allow sub-classing Request and add_request_method, fixes #1529

### LINKED ISSUE #1529: Cannot subclass Request and use add_request_method
See this test:

```python

class TestPyramidRequestProperties:

    def test_it(self):
        from pyramid.request import Request
        from zope.interface import providedBy, implementedBy

        req = Request({})
        assert providedBy(req) == implementedBy(Request)

        req._set_properties({'b':'b'})

        assert providedBy(req) == implementedBy(Request)

    def test_subclassing(self):
        from pyramid.request import Request
        from zope.interface import providedBy, implementedBy

        class Subclass(Request):
            pass

        req = Subclass({})

        #calling providedBy(req) makes the test pass
        #providedBy(req)
    
        #assert providedBy(req) == implementedBy(Subclass)

        req._set_properties({'b':'b'})

        assert providedBy(req) == implementedBy(Subclass)

```

This is the output from the test:
```
Traceback (most recent call last):
  File "test_request.py", line 111, in test_subclassing
    assert providedBy(req) == implementedBy(Subclass)
AssertionError: assert <implementedB...uiltin__.type> == <implementedBy...uest.Subclass>
  Full diff:
  - <implementedBy __builtin__.type>
  + <implementedBy kotti.tests.test_request.Subclass>
```

And this is the difference from a normal request to one that has been "decorated" by _set_properties:

```

(Pdb) pp vars(providedBy(req))
{'__bases__': (<implementedBy __builtin__.object>,),
 '__iro__': (<InterfaceClass zope.interface.Interface>,),
 '__name__': '__builtin__.type',
 '__sro__': (<implementedBy __builtin__.type>,
             <implementedBy __builtin__.object>,
             <InterfaceClass zope.interface.Interface>),
 '_implied': {<InterfaceClass zope.interface.Interface>: (),
              <implementedBy __builtin__.object>: (),
              <implementedBy __builtin__.type>: ()},
 'dependents': <WeakKeyDictionary at 140434285597760>,
 'inherit': <type 'type'>}

(Pdb) pp vars(providedBy(Subclass({})))
{'__bases__': (<implementedBy pyramid.request.Request>,),
 '__iro__': (<InterfaceClass pyramid.interfaces.IRequest>,
             <InterfaceClass zope.interface.Interface>),
 '__name__': 'kotti.tests.test_request.Subclass',
 '__sro__': (<implementedBy kotti.tests.test_request.Subclass>,
             <implementedBy pyramid.request.Request>,
             <InterfaceClass pyramid.interfaces.IRequest>,
             <InterfaceClass zope.interface.Interface>,
             <implementedBy webob.request.BaseRequest>,
             <implementedBy pyramid.url.URLMethodsMixin>,
             <implementedBy pyramid.request.CallbackMethodsMixin>,
             <implementedBy pyramid.util.InstancePropertyMixin>,
             <implementedBy pyramid.i18n.LocalizerRequestMixin>,
             <implementedBy pyramid.security.AuthenticationAPIMixin>,
             <implementedBy pyramid.security.AuthorizationAPIMixin>,
             <implementedBy __builtin__.object>),
 '_implied': {<InterfaceClass pyramid.interfaces.IRequest>: (),
              <InterfaceClass zope.interface.Interface>: (),
              <implementedBy kotti.tests.test_request.Subclass>: (),
              <implementedBy pyramid.request.Request>: (),
              <implementedBy webob.request.BaseRequest>: (),
              <implementedBy pyramid.url.URLMethodsMixin>: (),
              <implementedBy pyramid.request.CallbackMethodsMixin>: (),
              <implementedBy pyramid.util.InstancePropertyMixin>: (),
              <implementedBy pyramid.i18n.LocalizerRequestMixin>: (),
              <implementedBy pyramid.security.AuthenticationAPIMixin>: (),
              <implementedBy pyramid.security.AuthorizationAPIMixin>: (),
              <implementedBy __builtin__.object>: ()},
 'dependents': <WeakKeyDictionary at 140434219857464>,
 'inherit': <class 'kotti.tests.test_request.Subclass'>}
```

In the first test, ``test_it``, the ``req`` variable has 'proper' providedBy information, only by subclassing the problem appears.

### PR DESCRIPTION
**Pull request by bertjwregeer**
I wrote some additional tests to try and track down what was going on, on top of that I've applied a fix that seems to work.

Fixes: https://github.com/Pylons/pyramid/issues/1529

### CODE REVIEW

**Comment by bertjwregeer** [comment]
I would be very interested in seeing if the reporters from https://github.com/Pylons/pyramid/issues/1067 and https://github.com/Pylons/pyramid/issues/1212 could see if this change makes any difference.

@mmerickel @tseaver @mcdonc @davisagli please take a look, and see if this is right or if this will cause memory leaks again.

**Comment by mcdonc** [comment]
The only way to determine if this causes a memory leak is to set up a test like that described in the first issue on #1212 .

**Comment by mcdonc** [comment]
(can't tell by simple inspection, the machinery is too complex)

**Comment by mcdonc** [comment]
@bertjwregeer in https://github.com/Pylons/pyramid/issues/1529#issuecomment-73380216 you say "I am not seeing any increase in memory usage" after the application of this PR.  Can I ask how you determined that?

**Comment by bertjwregeer** [comment]
@mcdonc When I remove the original addition of the copying of `__provides__`, `__implemented__` and `__providedBy__`, I see the `id()` for those values change, and memory is allocated, and the old values continue to exist.

With the patch you made, calling `providedBy()` doesn't allocate new memory and the `id()` stays the same, however `_set_properties()` breaks.

Removing `__providedBy__` from the list of copies, it will get added again after a call to `providedBy()`, but it is the original one from the class we are sub-classing, so no additional memory will have been allocated (`id()` matches)

I haven't had a chance to go test it like the initial bug report and verify that it really doesn't affect anything, and I wish there was a simple sample project that showed how to do the sort of testing the original poster did.

**Comment by mcdonc** [comment]
OK thanks @bertjwregeer i'll set up the rig to do the testing with your patch applied;  I just wanted to see if you had already done  that.  I think we need to do  it as a "functional test" because the machinery is so complex.

**Comment by bertjwregeer** [comment]
Thanks for merging this :-).

**Pull request merged**
