### PR TITLE
Delete duplicate getargspec imports

### PR DESCRIPTION
**Pull request by berkerpeksag**

### CODE REVIEW

**Comment by mmerickel** [comment]
LGTM

**Comment by bertjwregeer** [comment]
Could you please sign CONTRIBUTORS.txt?

**Comment by tseaver** [comment]
@bertjwregeer 

> Could you please sign CONTRIBUTORS.txt?

Not a bad thing, certainly, but a PR which only removes lines cannot be a copywritable contribution, almost by definition.

**Comment by mmerickel** [comment]
He already signed it in his other PR that I signed off on.

**Comment by bertjwregeer** [comment]
I'm hoping he keeps coming back :P

**Comment by bertjwregeer** [comment]
👍

**Pull request merged**
