### PR TITLE
Added super basic Alembic configuration to the alchemy paster template

### PR DESCRIPTION
**Pull request by nek4life**
Created a super basic alembic configuration for the alchemy paster template for issue https://github.com/Pylons/pyramid/issues/1597. I'd like to get feedback on the approach and whether or not this is something to be pursued. If so I'll go ahead and create tests and documentation to go along with the patch. I will likely need help writing tests for the template output as it doesn't seem as straight forward as writing a regular unit test.

### CODE REVIEW

**Comment by blaflamme** [comment]
@mmerickel BTW should we agree to update the pattern used for SQLA to something similar to this?

https://gist.github.com/blaflamme/0b25c8fed8db0b87b9b6

**Comment by nek4life** [comment]
Back home now... 

So I guess there are still a few things to decide. 

* Should the migrations be located inside or outside of the package.
* Should the folder name be alembic or migrations.
* Should the sqlalchemy be located in the [DEFAULT] section or remain under the [app:main] section in which case the alembic env.py will need to be modified to support this use case.

And there is the matter of testing. I'm currently unsure how to create the necessary tests for the resulting output of the paster templates. I'll try to dig into the code a bit to see what kind of tests are currently written for the paster templates.

**Comment by pauleveritt** [comment]
You could switch to Wichert’s pyramid_sqlalchemy.

—Paul

**Comment by nek4life** [comment]
@pauleveritt I could be mistaken but I didn't see any Alembic support with the pyramid_sqlalchemy package. I also think there was some discussion about setting up the paster template with a non global (or non scoped I think in sqlalchemy lingua.)

BTW is there separate ticket for that?

**Comment by pauleveritt** [comment]
Sorry about that, I was responding to Blaise’s ticket about SQLA setup in Pyramid. You’re right that the topic should be in a different ticket.

—Paul

**Comment by blaflamme** [comment]
@pauleveritt the discussion we had with @mmerickel and others was about avoiding to use sqla's scoped_session for the better

**Comment by marioidival** [comment]
I was hoping someone comment on that issue in which I created, but thank you for making this PR @nek4life

**Comment by ergo** [comment]
What's the consensus on the issue right now?
I think all actual features of new scaffold are implemented so I could also incorporate alembic to it.

**Comment by marioidival** [comment]
@ergo It's nice :+1:

**Comment by lmctv** [comment]
@ergo :+1: from me, even though documentation is completely missing.

**Comment by mmerickel** [comment]
The alchemy scaffolding changes are already massive. I'm pretty afraid to merge this until that dust has settled. In general I'm not particularly excited about merging an alembic setup into pyramid's core scaffold at all but it seems like the idea has a fair amount of support.

Work that needs to be done here to have a hope of merging:

- [ ] Update the `src` folders in the `wiki2` tutorial as they are derived from the scaffold.
- [ ] Update the `wiki2` tutorial to contain an explaination of how to use and modify the setup to perform migrations.

Chicken-and-the-egg here: these changes will likely be easier to do after waiting until the other scaffold changes are complete in #2024.

**Comment by ergo** [comment]
I have also my own solution to alembic - one that integrates with initialize_db script - so no work would be required on tutorials apart changing the location initial model migration.

I'm more concerned about the fact that alembic will not work with sqlite at all - if memory serves me right.

**Comment by mmerickel** [comment]
Alembic has grown support for SQLite over the years but it does have a few quirks as can be expected. 

> so no work would be required on tutorials apart changing the location initial model migration.

I'm saying someone **MUST** update the tutorial to explain the features. :-)

**Comment by hyperknot** [comment]
I might have a look at this project and try to integrate inklesspen's project and the new 1.7 compatibility changes.

**Comment by mmerickel** [comment]
This work should be done on the cookiecutter. Anyone is welcome to contribute alembic support there.

**Pull request closed without merging**
