### PR TITLE
Scaffolds: allow pytest run without args

### PR DESCRIPTION
**Pull request by vincent-ferotin**
Here is pull request related to this thread: https://groups.google.com/forum/#!topic/pylons-devel/AIqmefG6eIE ,
to allow usage of raw `py.test` command (without arguments) at newly created project's root by scaffolds.

Changes add two new files to scaffolds:

- `pytest.ini` for pytest configuration, which set package as test path, scanning for all `*.py` files;
- `.coveragerc` for coverage configuration, setting package to cover, and omitting tests files following `test*` pattern (for allowing ``py.test --cov`` invocation).

### CODE REVIEW

**Comment by mmerickel** [comment]
I'm happy with this. I would have preferred to use `setup.cfg` since we use that for other things but since we don't use it anymore in the scaffolds this is an acceptable location and a bit more explicit for users to discover.

+1

**Comment by vincent-ferotin** [comment]
Thanks!

**Comment by mmerickel** [comment]
We need to rebase this on top of #2546 and update the docs accordingly. ping @stevepiercy It looks like you made that PR incompatible with these changes so can you help resolve them?

**Comment by stevepiercy** [comment]
LGTM so far. We need to update any docs that use `py.test` and scaffolds, which includes off the top of my head, Quick Tour, Quick Tutorial, wiki, and wiki2. @mmerickel I'll take this on and backport from master to 1.7. Weekend plans got cancelled, so I have nothing better to do.

@vincent-ferotin have you signed [contributors.txt](https://github.com/Pylons/pyramid/blob/master/CONTRIBUTORS.txt)? If not, please do so, commit, and push to your branch. That should automatically update this PR.

**Comment by stevepiercy** [comment]
I created a new branch https://github.com/Pylons/pyramid/tree/vincent-ferotin-scaffolds-allow-pytest-run-without-args that replaces this PR, and gives me a place to push additional work on docs.

@vincent-ferotin please sign [contributors.txt](https://github.com/Pylons/pyramid/blob/master/CONTRIBUTORS.txt) if you have not yet done so, and push the commit to that new branch. The PR #2550 will update automatically. Thank you!

**Pull request closed without merging**
