### PR TITLE
setDaemon attribute was deprecated in Python 3.10.

### LINKED ISSUE #3676: threading.Thread.setDaemon has been deprecated in favor of setting daemon attribute directly in Python 3.10
https://github.com/Pylons/pyramid/blob/8061fce297cc7117d3e6e2b39e47512c7db2904f/src/pyramid/scripts/pserve.py#L234

Ref : python/cpython#25174

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #3676

### CODE REVIEW

**Comment by stevepiercy** [comment]
@tirkarthi thank you for the PR. Would you please also sign https://github.com/Pylons/pyramid/blob/master/CONTRIBUTORS.txt, commit, and push to the PR?

The failing GitHub Workflow is due to a new version of Black reformatting docstrings, but that's not because of your contribution. We need to run Black on a new separate PR.

**Comment by tirkarthi** [comment]
Thanks, signed and pushed,

**Review by stevepiercy — APPROVED** [review]

**Comment by stevepiercy** [comment]
I'd like an approval from another maintainer, or just a merge. Then I will backport, add change notes, and run a separate PR for the black issue.

**Comment by bertjwregeer** [comment]
Thank you!

**Pull request merged**
