### PR TITLE
Correct hyperlinks in logging.rst

### PR DESCRIPTION
**Pull request by stkyle**
Correct broken links to logging FileHandler and logging RotatingFileHandler

### CODE REVIEW

**Comment by stevepiercy** [comment]
Thank you!

**Comment by mmerickel** [comment]
Can we use an intersphinx link here instead? Something like 

```
:class:`logging.handlers.RotatingFileHandler`
```

**Comment by mmerickel** [comment]
Oh, steve merged it. Ok.

**Comment by stevepiercy** [comment]
Good idea. I will use intersphinx. I think that's better than a link to a fixed version of Python.

I will also cherry pick to master. I'll do that later tonight.

**Comment by stevepiercy** [comment]
Done in #1539 and #1540

**Pull request merged**
