### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by ergo**

### CODE REVIEW

**Review by stevepiercy — COMMENTED** [review]
Should we also drop Python 3.6 which is EOLed?

**Comment by stevepiercy** [comment]
For build failures see https://github.com/Pylons/pyramid/issues/3684

**Comment by ergo** [comment]
Removed 3.6 tests from tox.

**Comment by ergo** [comment]
All green :)

**Review by stevepiercy — APPROVED** [review]
Nice work. Thank you!

**Comment by stevepiercy** [comment]
I requested a review from @mmerickel and to decide whether to merge.

**Comment by russellballestrini** [comment]
thx team ❤️

@ergo
@stevepiercy
@bertjwregeer

**Pull request merged**
