### PR TITLE
Extra colon in docs breaks code block highlighting.

### PR DESCRIPTION
**Pull request by ianjosephwilson**
2cc0710ecf9b47e5a6f41caf6b1c56b29bab2db0

### CODE REVIEW

**Comment by mmerickel** [comment]
LGTM, ping @stevepiercy

**Comment by stevepiercy** [comment]
In addition to removing the extra colon, the lexer is incorrect. It should be [pycon](http://pygments.org/docs/lexers/#pygments.lexers.python.PythonConsoleLexer) for Python console.

I used a grep search `\:\:\s+\.\.` to find any other potential candidates for correction, and found no others.

**Comment by mmerickel** [comment]
nice I didn't know about that lexer option

**Comment by stevepiercy** [comment]
Actually only needed backporting to 1.6, as this code was added in 1.6.

**Pull request merged**
