### PR TITLE
Added support for a prefixed base url that does not contain a trailing slash

### PR DESCRIPTION
**Pull request by nek4life**
This was simply a behavior I wanted so I went through to see if I could accomplish hacking on pyramid to make it so. Pyramid's current behavior when supplying an empty string is to match the root of the domain I think this behavior should be carried through to routes with a route prefix. At first I wanted to match both an empty string and '/' but that would break a lot of existing applications that depend on the current behavior.

Right before submitting this patch I looked and found a long discussion for issue #406 which in hindsight I should have read prior to doing this work. I will go back and read through the discussion to see if what I changed makes sense based on the content there.

### CODE REVIEW

**Comment by mmerickel** [comment]
This is in the discussion for Pyramid 2.0 and I personally think this is a good approach despite it being somewhat bw incompatible. That being said you haven't signed the CONTRIBUTORS.txt agreement yet so I'm closing this for now. If you want to push such a commit we can keep it open.

**Comment by nek4life** [comment]
Hey @mmerickel I'd definitely like to see this functionality for Pyramid 2.0. Are you suggesting merging this prior to that despite it being somewhat bw incompatible or waiting until 2.0? The only reason I ask is I tried to make this semi backwards compatible while getting the new functionality, but I'm wondering if it's for Pyramid 2.0 then would you consider going full backwards incompatible and this merge only being a half measure?

In either case. If this is to be merged I've updated my branch to include my signature to the contributors agreement. I can open a new pull request, just let me know.

Thanks for following up.

**Comment by mmerickel** [comment]
@nek4life If you push to your branch it should update this PR automatically unless Github has gotten confused.

The only incompatibility that I see is in what `''` means for `config.add_route`. I was avoiding revisiting this issue myself until 2.0 probably but noticed that the PR couldn't be used as is without your signature while I was pruning the backlog.

**Comment by mmerickel** [comment]
Ok it found the commit after I reopened the PR.

**Comment by nek4life** [comment]
I agree in it's current form setting an empty string isn't immediately obvious. However, it was in my list of things to try since when I added '/' it appended a slash to the end of the url. So FWIW my first instinct was to replace the slash with an empty string expecting for it to be removed when I did so. At least this way there is an option to remove it from url when the route is prefixed by a group.

Thanks for opening the request back up.

**Comment by mmerickel** [comment]
replaced by #3415

**Pull request closed without merging**
