### PR TITLE
expect py3 and special-case py2 behavior

### PR DESCRIPTION
**Pull request by mmerickel**
previously py3 was the special case, but as we move toward the future we
want the py2 codebase to be considered legacy with py3 as the default

### CODE REVIEW

**Comment by stevepiercy** [comment]
This is a good idea. Off the top of my head, I can't think of any Python version specific docs that require updating.

**Comment by tseaver** [comment]
LGTM

**Comment by bertjwregeer** [comment]
While I don't disagree with the change, I am wondering if this actually changes any aspect of the runtime efficiency? Does Python do any optimizations based upon which side of the branch it needs to take?

The code change looks good to me.

**Comment by mmerickel** [comment]
Almost all of the changes are import-time. As far as if/else efficiency I've never heard of python attempting to do any branch prediction on top of what the CPU would be doing itself.

**Comment by abdulmuneer** [comment]
if there is any explicit version check for python 3 (like sys.version[0]==3), it is going to execute python 2 code when python version reaches 4.

**Comment by bertjwregeer** [comment]
Before that happens, we will have deprecated Python 2.x.

**Pull request merged**
