### PR TITLE
Vincent ferotin scaffolds allow pytest run without args

### PR DESCRIPTION
**Pull request by stevepiercy**
Replaces #2545.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@mmerickel I'm not sure on which branch and which file this change note should go:

```rst
- Add defaults for py.test configuration and coverage to all three scaffolds,
  and update documentation accordingly.
  See https://github.com/Pylons/pyramid/pull/2550
```

**Comment by stevepiercy** [comment]
@vincent-ferotin your signing of [contributors.txt](https://github.com/Pylons/pyramid/blob/master/CONTRIBUTORS.txt) is the final piece to this PR.

**Comment by mmerickel** [comment]
@stevepiercy it is just reported as a change from 1.7b2 to 1.7b3 in the 1.7-branch changelog.

**Comment by vincent-ferotin** [comment]
In PR #2558 I fixed some typos and signed contributor agreement.
Thanks for your patience, and bravo to Steve for updating all documentation regarding this PR.

**Comment by stevepiercy** [comment]
@vincent-ferotin thank you for your collaboration. I'll backport this to 1.7-branch.

**Pull request merged**
