### PR TITLE
remove dead link

### PR DESCRIPTION
**Pull request by adamcheasley**
Looks like plope.com is now dark.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@mcdonc plope.com is not responding. What's up with it?

**Comment by tseaver** [comment]
I'm in the process of decommissioning its host, so it should be moving shortly. It may have crashed while I was poking around.  Can we hold off on merging this until Chris and I have a chance to confer?

**Comment by mmerickel** [comment]
I think it's actually been down for quite a while. I had assumed that Chris just killed it already. I've tried to open the posts often in the last year and only remember tcp connection errors.

**Comment by mmerickel** [comment]
Can we just replace the dead plope.com links with webarchive? https://web.archive.org/web/20170131192830/http://www.plope.com/weird_pyramid_urldispatch

**Comment by mmerickel** [comment]
Fixed in 681a79f56.

**Pull request closed without merging**
