### PR TITLE
set pyramid_tm.explicit_manager in the configuration

### PR DESCRIPTION
**Pull request by chrismorales**

### CODE REVIEW

**Comment by stevepiercy** [comment]
@chrismorales 1 down, 2 to go.

> * docs/tutorials/wiki/src/*/tutorial/models/__init__.py (6 files)
> * in docs/tutorials, a regex search of literalinclude.*__init__.py found 20 matches in 5 files that need to be reviewed for possible line number realignment

**Comment by mmerickel** [comment]
Is this done? I will probably try to finish this and add in #3048 and #3042 at the same time if I can find a block of time this weekend. These issues are the only real hold up to a new release right now.

**Comment by stevepiercy** [comment]
If I don't hear anything from @chrismorales today, I'll pick this up, probably late tonight.

**Comment by mmerickel** [comment]
Ok well like I said the other 2 issues I linked are the same thing so everything should probably be done at once for simplicity with the exception that this PR is almost complete so maybe just finish it off and then do the other 2 as one change.

**Comment by stevepiercy** [comment]
Yup, that's my plan.

**Comment by stevepiercy** [comment]
Refs #3052

**Pull request merged**
