### PR TITLE
Fix #2548, add SRI has for script tags

### LINKED ISSUE #2548: use integrity attribute for javascripts from CDN
Our scaffolds and possibly other items reference jQuery without an integrity attribute. From http://jquery.com/download/#jquery-39-s-cdn-provided-by-maxcdn

> The jQuery CDN supports https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity (SRI) which allows the browser to verify that the files being delivered have not been modified. This https://www.w3.org/TR/SRI/ is currently being implemented by browsers. Adding the new integrity attribute will ensure your application gains this security improvement as browsers support it.

``` html
<script
   src="https://code.jquery.com/jquery-1.12.3.min.js"
   integrity="sha256-aaODHAgvwQW1bFOGXMeX+pC4PZIPsvn2h1sArYOhgXQ="
   crossorigin="anonymous"></script>
```

### PR DESCRIPTION
**Pull request by fangpenlin**

### CODE REVIEW

**Comment by stevepiercy** [comment]
See my [comment on #3055](https://github.com/Pylons/pyramid/issues/2548#issuecomment-303248109) before merging.

**Comment by fangpenlin** [comment]
@stevepiercy done

**Comment by fangpenlin** [comment]
please let if know if there is anything else missing

**Comment by stevepiercy** [comment]
Who's awesome? YOU ARE! Thank you @fangpenlin!

I'll do the backport to 1.8.

**Pull request merged**
