### PR TITLE
This shows the correct view when a class and `attr` is involved.

### PR DESCRIPTION
**Pull request by sontek**

### CODE REVIEW

**Comment by sontek** [comment]
Before this change:

```
class_based_view           /classes                test_pyramid_apps.standard_views.ClassBasedView             POST
```

and after:

```
class_based_view           /classes                test_pyramid_apps.standard_views.ClassBasedView.awesome_attr    POST
```

**Comment by stevepiercy** [comment]
Nice.

For completeness, should either of these be updated? 
* `proutes.py` docstrings
* http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#displaying-all-application-routes

Also a change log entry?

**Comment by stevepiercy** [comment]
Sorry, my bad aim on clicking buttons.

**Comment by sontek** [comment]
@stevepiercy Nope, the docs are accurate, there was just this tiny little bug when you used a class + `attr`, this is how it should have worked from the beginning :)

**Comment by stevepiercy** [comment]
@sontek LGTM.

Should this bug fix be backported to 1.7 and 1.6, along with change log entries?

**Comment by sontek** [comment]
@stevepiercy Yeah, I think it'd be a great candidate for a backport

**Comment by mmerickel** [comment]
LGTM. This feature is fine to be backported if you want to submit the PRs and changelog entries for them.

**Comment by stevepiercy** [comment]
I'll do backports tomorrow.

**Pull request merged**
