### PR TITLE
Issue #2493: Fixing Quick Tutorial Step 18 - CSS/JS Paths

### PR DESCRIPTION
**Pull request by arianmaykon**
Fixed CSS and JS paths, and removed JQuery (already included by Deform).

### CODE REVIEW

**Comment by mmerickel** [comment]
LGTM

**Comment by stevepiercy** [comment]
@arianmaykon nice catch! Would you please sign [CONTRIBUTORS.txt](https://github.com/Pylons/pyramid/blob/master/CONTRIBUTORS.txt)? Then I'll merge the PR. Thank you!

**Comment by stevepiercy** [comment]
Note to self: also apply to `databases` step, and backport to 1.6-branch.

**Comment by arianmaykon** [comment]
Sure, thanks by the way

**Comment by stevepiercy** [comment]
@arianmaykon thanks for taking care of databases, too!

**Pull request merged**
