### PR TITLE
docs: refresh ZODB wiki tutorial

### PR DESCRIPTION
**Pull request by tseaver**
rendered: https://pylons--3751.org.readthedocs.build/projects/pyramid/en/3751/tutorials/wiki/index.html

### CODE REVIEW

**Review by mmerickel — CHANGES_REQUESTED** [review]
- I caught a missed reference to setup.py in the design chapter.
- In definingviews I caught `We need to add a dependency on the docutils package to our tutorial package's pyproject.toml file by assigning this dependency to the requires parameter in the setup() function.` referencing the `setup()` function.
- In tests chapter I caught several references to `pytest.ini` and `.coveragerc`. Might want to pull some of that language from [here](https://github.com/Pylons/pyramid/pull/3747/files#diff-b368cc66e86b29a42dacbaf6c0bca9f69dbcf1c17467cda3f706b613a6c67aaa) if it's helpful.
- We had [similar but different language](https://github.com/Pylons/pyramid/pull/3747/files#diff-7d8cd3526103d0a3d9fbf854d708ac72e00e5cc61db9edacd374e21413075bec) around distributing your application. I think we should combine the good from both.

**Comment by mmerickel** [comment]
I pushed a version that merges things together here if you want to use it. https://raw.githubusercontent.com/Pylons/pyramid/b2c8840708079ad645cd7abea45634d4b8686eb8/docs/tutorials/wiki2/distributing.rst

**Comment by mmerickel** [comment]
And tweaks to installation.rst for wiki2 here https://github.com/Pylons/pyramid/pull/3747/commits/a31db999eaecb393b1d0c10058b1d43be076a4f6

**Comment by tseaver** [comment]
@mmerickel I've cleaned up the remaining `setup()` / `setup.py` mentions, and folded in your language for `Distrinbuting` and `Installation`.

**Review by mmerickel — APPROVED** [review]

**Pull request merged**
