### PR TITLE
Move notify for NewResponse for symmetry with other event exception h…

### PR DESCRIPTION
**Pull request by ericatkin**
…andling

### CODE REVIEW

**Comment by bertjwregeer** [comment]
@ericatkin could you provide some more context/colour around this change? As it stands now I am not sure what exactly this is changing, or what bug this is fixing.

How does that affect this diagram: https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/router.html?

**Comment by ericatkin** [comment]
This moves the NewResponse event to the Router.handle_request() method so that exceptions in such events are handled in the same way as NewRequest, BeforeTraversal, and ContextFound (by tweens). As it is, I don't see any way to catch exceptions in NewResponse handlers.

With regard to the diagram, it would move NewResonse above the egress tween node. I don't know how to update that.

**Comment by huntcsg** [comment]
The existing behavior is part of the documented public API. See the docs for [pyramid.request.Request.add_response_callback](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.add_response_callback):

> All response callbacks are called after the tweens and before the [pyramid.events.NewResponse](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/events.html#pyramid.events.NewResponse) event is sent.

Instead of making this change would you be able to register a tween at the correct position to accomplish whatever you are attempting to do in your `NewResponse` listener?

If that is impractical would it make sense to add an additional event/events that you could listen for instead of `NewResponse`?

**Comment by ericatkin** [comment]
Yeah, now that I understand tweens, a tween under EXCVIEW works for me, but I found it surprising that NewResponse happens outside of the EXCVIEW tween as opposed to the other events. I imagine that would break a lot of code to move it as I proposed.
Thanks.

**Pull request closed without merging**
