### PR TITLE
The Configurator object should not alter the input settings dict object.

### PR DESCRIPTION
**Pull request by Natim**
Test showing #2958 behavior.

### CODE REVIEW

**Comment by mmerickel** [comment]
Can you please rewrite your commits without GPG signatures? I'm pretty confident we don't have any other commits in our history with signatures and I'm concerned about allowing them without a discussion on the implications. I'd rather avoid that for now.

If we need to have this discussion because you feel so strongly about it then it'll have to wait until I have time to do more research, meaning this fix doesn't get applied for longer.

**Comment by Natim** [comment]
Signed commit shouldn't cause you any trouble but I will change that ok.

**Comment by mmerickel** [comment]
Thank you @Natim !

**Pull request merged**
