### PR TITLE
Clarify that the string 'None' should be the value for `samesite`

### PR DESCRIPTION
**Pull request by stevepiercy**
- See https://github.com/Pylons/pyramid/issues/2733#issuecomment-672936565

### CODE REVIEW

**Comment by stevepiercy** [comment]
If this is good, then it should be backported to 1.10 and 1.09.

**Comment by bertjwregeer** [comment]
This is good.

**Comment by bertjwregeer** [comment]
Also, validate that it needs to be ported to 1.09, I am not sure when we introduced support for `SameSite='none'`

**Comment by stevepiercy** [comment]
Yup, 1.10 only, not 1.9. Thanks for the review.

**Pull request merged**
