### PR TITLE
Add more badges

### PR DESCRIPTION
**Pull request by armab**
l6x9xhc 1

Could be more useful for those who checking the project from time to time in GitHub.

### CODE REVIEW

**Comment by stevepiercy** [comment]
Thanks for this. I need to check with some of the core contributors which versions and branches should have badges, if any. The terminology of latest, master, and other non-numeric release and branch names can be confusing.

**Comment by stevepiercy** [comment]
@armab after a [brief discussion about badges in #pyramid](https://botbot.me/freenode/pyramid/2015-03-26/?msg=35074798&page=1), I'm closing this PR in favor of another to add a badge and link to docs latest. Thanks for bringing up the issue.

**Comment by armab** [comment]
@stevepiercy thanks for fast reaction.

Does it makes sense to fill another PR and add code coverage badge via https://coveralls.io/ ?

Like: 
code coverage for master
-----

All that provides really good brief overview on latest project state not only for those who choosing framework for next project, but also for possible contributors

**Comment by stevepiercy** [comment]
I would say no, because the service requires the owner of the Pylons account to authorize usage, and even though there is no fee to FOSS projects, it still has a bad smell. Avoid entanglements.

**Comment by armab** [comment]
But the owner already granted access for Travis-CI.

How about http://scrutinizer-ci.com/ (it has code coverage feature too) or it's kind of avoiding using 3rd party services when possible?

**Comment by stevepiercy** [comment]
For those who care about code coverage:
http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/introduction.html?highlight=coverage#testing
https://github.com/Pylons/pyramid/blob/master/HACKING.txt#L65-L67
Example: https://travis-ci.org/Pylons/pyramid/jobs/55902353

We do not need yet another service.

**Comment by armab** [comment]
My point is mostly about popularization.

My thinking is: If you care about coverage, why not to show that in easy way. There are very few frameworks with so good coverage. if you support different python versions - why not to show that easily, the same is about popularity or latest release version.
From user's (already framework consumer or possible framework consumer) perspective it has sense.

But I understood your point, thanks for the explanation and your contribution to make `pyramid` awesome.

**Pull request closed without merging**
