### PR TITLE
remove pypy3 from the testing matrix and docs

### PR DESCRIPTION
**Pull request by stevepiercy**
refs #2871

### CODE REVIEW

**Comment by stevepiercy** [comment]
Tests for py26 are failing now. Perhaps pin webtest to 2.0.23 for pyramid 1.6?
https://github.com/Pylons/webtest/blob/master/CHANGELOG.rst

**Comment by mmerickel** [comment]
It only really needs to be dropped from the travis test matrix. It runs fine on pypy3... just not the version on travis.

As far as webtest I would pin waitress itself to < 1.0 instead.

**Comment by bertjwregeer** [comment]
Ah, looks like webtest now requires Python 2.7 or higher, waitress shouldn't have broken Py2.6 compat, it's just no longer officially supported.

**Comment by mmerickel** [comment]
> Ah, looks like webtest now requires Python 2.7 or higher, waitress shouldn't have broken Py2.6 compat, it's just no longer officially supported.

Yes, I saw that but if you read the webtest changelog it says "newer versions may still work if you pin waitress < 1.0" so I went for the quick fix. However, webtest stopped installing ordereddict on py26 which broke things as well so the changelog was a bit deceiving / not quite clear on how much you had to do to make it work on 2.6.

**Pull request merged**
