### PR TITLE
Backport #3657

### PR DESCRIPTION
**Pull request by luhn**

### CODE REVIEW

**Comment by luhn** [comment]
Builds were failingbecause `ubuntu-latest` has been updated to 20.04, which doesn't support Python 3.4.  So I pinned the tests to `ubuntu-18.04`.

**Comment by stevepiercy** [comment]
[Building docs test](https://github.com/Pylons/pyramid/pull/3658/checks?check_run_id=1922958925) seems to have stalled after 22 minutes. Should I restart the jobs?

**Comment by luhn** [comment]
I guess so.

I wonder if Github is having some issues.  A coworker had a test stuck in the queue for 30 minutes earlier today.

**Comment by stevepiercy** [comment]
Restarted. The docs job had started, and stalled just after loading the .inv file from SQLAlchemy. All jobs pass now.

**Comment by mmerickel** [comment]
Oh come on I forgot to look at this before releasing 1.10.6. FML

**Comment by mmerickel** [comment]
@luhn any chance you could rebase this and use the CI that I did for 1.10-branch instead of this? I think I prefer my change that keeps running tests against latest for the most part.

**Comment by luhn** [comment]
Done.

**Comment by mmerickel** [comment]
Thank you @luhn !!!

**Pull request merged**
