### PR TITLE
Add one-way password hash to security example in Wiki Tutorial.

### PR DESCRIPTION
**Pull request by cjltsod**
This pull-request is aiding #2204.
The usage of hashlib for one-way hash is from the discussion of #2590.

### CODE REVIEW

**Comment by cjltsod** [comment]
The travis-ci docs build failed is because of that http://docs.zope.org/zope.component/objects.inv' is unreachable.

**Comment by ztane** [comment]
new in version 3.4. I am all for it, yes, though.

**Comment by stevepiercy** [comment]
Please see my comments in PR #2699.

**Comment by stevepiercy** [comment]
Closing this because we hashed out (ha!) a fix for wiki2 in #2704. Please base your work off the example using bcrypt. Thank you!

**Pull request closed without merging**
