### PR TITLE
When running pcreate without scaffold, list scaffolds

### LINKED ISSUE #1297: Suggestion: pcreate should list the template part of basic usage

### PR DESCRIPTION
**Pull request by bertjwregeer**
This fixes #1297

### CODE REVIEW

**Comment by mmerickel** [comment]
tests are failing

**Comment by bertjwregeer** [comment]
That's what I get for making too many changes... give me a second, and I'll fix it.

**Comment by bertjwregeer** [comment]
Test should be fixed.

**Comment by mmerickel** [comment]
Green checkmark! Ship it!

**Pull request merged**
