### PR TITLE
[WIP] Increase Quick Tutorial test coverage to 100%

### PR DESCRIPTION
**Pull request by keitheis**
## TODO
- [ ] Recheck all quick tutorials coverage
- [ ] Fix no 100% coverage tutorials

## Maybe
- [ ] Proposal a test to automate the check

### CODE REVIEW

**Comment by stevepiercy** [comment]
Thank you for your work on this!

Is this truly a WIP or ...? I slapped on the "do-not-merge" label until I hear back.

**Comment by keitheis** [comment]
@stevepiercy yes still WIP, currently verified the commit and not yet checking tutorials after `more_view_classes`. Will continue after flight back.

**Comment by stevepiercy** [comment]
@keitheis we're approaching a release for Pyramid 1.10. Will you have some time to complete work on this PR within the next few weeks? If so, then I'll add this to the 1.10 milestone. Please let me know. Thank you!

**Comment by mmerickel** [comment]
I'm going to close this soon due to inactivity.

**Pull request closed without merging**
