### PR TITLE
- update Pyramid Request Processing Diagram.

### LINKED ISSUE #2473: update Pyramid Request Processing diagram
Update Pyramid Request Processing diagram after the dust settles. See:

- [ ] #2413 - Add a yellow box for the CSRF checks between `authorization` and `decorators ingress` in the view pipeline.
- [ ] #2469 - Add a purple box for the new event, `BeforeTraversal`, and place it just to the right of the green URL dispatch box in the Request Processing diagram.

Ping @mmerickel and @bertjwregeer to confirm these and any other possible revisions for 1.7 release.

### PR DESCRIPTION
**Pull request by stevepiercy**
- Closes #2473.
- See also #2413 and #2469.
ping @bertjwregeer @mmerickel

### CODE REVIEW

**Comment by mmerickel** [comment]
Ah, BeforeTraversal is an event, it goes between blocks similar to ContextFound... it should be on the line between route predicates and traversal.

**Comment by mmerickel** [comment]
Also personally I think "csrf checks" fits the style better than "CSRF checks". Similarly "url dispatch" instead of "URL dispatch". Those 2 just look weird now! Just one man's opinion though.

**Comment by stevepiercy** [comment]
Updated placement of `BeforeTraversal`.

Sorry, I just can't bring myself to lowercase acronyms.

**Comment by mmerickel** [comment]
LGTM

**Pull request merged**
