### PR TITLE
Run cover inside coverage

### PR DESCRIPTION
**Pull request by sontek**

### CODE REVIEW

**Comment by mmerickel** [comment]
Amazing

**Comment by bertjwregeer** [comment]
Holy shit, that is the perfect image for this @mmerickel ... wow!

**Comment by sontek** [comment]
@mmerickel Tell me how you feel about #1571 in image form?

**Comment by mmerickel** [comment]
I can't bring myself to merge this until we ask holger if there's a better way to do this in tox.

**Comment by mmerickel** [comment]
I opened a ticket in tox to track this.

https://bitbucket.org/hpk42/tox/issue/238/group-envs-into-an-alias

**Pull request closed without merging**
