### PR TITLE
Including background how cache busting and CSS and JS resources play together

### PR DESCRIPTION
**Pull request by miohtama**
Added two simple examples of using cache busted URLs in CSS and JavaScript without additional tools required. This addresses #1654

### CODE REVIEW

**Comment by stevepiercy** [comment]
LGTM, but I would like one of the core developers who worked on this feature and docs to verify technical accuracy. @chrisrossi @mmerickel @mcdonc would you please review? I'll do any grammar, spelling, wordsmithing after a merge.

**Comment by mcdonc** [comment]
@stevepiercy this looks fine to me.  Can you merge into 1.6 and master and wordsmith?

**Comment by stevepiercy** [comment]
@mcdonc thanks. I'll do so.

**Comment by stevepiercy** [comment]
@miohtama thanks for the PR!

**Comment by miohtama** [comment]
Mahtavuutta :)

**Pull request merged**
