### PR TITLE
Make sure PServeCommand kwargs are passed to the hupper worker.

### PR DESCRIPTION
**Pull request by mmerickel**
Backport of #2962 to 1.8-branch.

### CODE REVIEW

**Comment by Natim** [comment]
Hi @mmerickel Would you have some bandwith to cut a 1.8.3 release with this fix please?

**Comment by bertjwregeer** [comment]
@Natim Are there any other issues that need fixing first? Cutting releases takes a bit of time and we don't want to have to spin 1.8.4 tomorrow...

**Comment by Natim** [comment]
If they were I would have filed PR...

**Comment by mmerickel** [comment]
> If they were I would have filed PR...

We were just referring to the last release when you opened a new bug report a day after, so it would be appreciated if you tested the unreleased 1.8-branch first to avoid anything obvious showing up immediately again. Plus you will get them fixed sooner without waiting a few weeks for another release.

Regardless, please don't take that as an insult, I certainly appreciate the bug reports. I will cut a release this weekend at the latest with the changes.

**Comment by stevepiercy** [comment]
@Natim releasing is not hard, it is merely time consuming. See our complete checklist, [RELEASING.txt](https://github.com/Pylons/pyramid/blob/master/RELEASING.txt).

If `zest.releaser` can automate all or most of all those details, I'd like to know more, but let's discuss in a new separate issue as a feature request.

**Comment by Natim** [comment]
Apparently we actually did :( https://github.com/Pylons/pyramid/issues/2975

**Comment by mmerickel** [comment]
@Natim that's a change of a default... that won't be going into a 1.8 bugfix release unfortunately.

**Comment by Natim** [comment]
Ok then we are good for 1.8.3

**Pull request merged**
