### PR TITLE
replace  ZopeTransactionExtension with zope.sqlalchemy.register

### PR DESCRIPTION
**Pull request by danduk82**
The new version of zope.sqlalchemy does not provide ZopeTransactionExtension anymore. As stated in [this official PR](https://github.com/zopefoundation/zope.sqlalchemy/pull/38)

This breaks the tutorial.

### CODE REVIEW

**Comment by stevepiercy** [comment]
This LGTM. Thank you!

Would you please sign [CONTRIBUTORS.txt](https://github.com/Pylons/pyramid/blob/master/CONTRIBUTORS.txt), if you have not done so already?

It appears that the failing build on Travis is due to the recent update in Black, and we can ignore that.

The failing build on Appveyor should be checked before merging this PR. It fails on Python 2.7. I have no idea why it should suddenly fail this catastrophically, and it appears unrelated to this PR, but I would like someone more informed than I to check, too.

Finally, would you make the PR against `master`, too? We generally prefer that development occur on master and we backport changes to other branches, but this is PR fine.

**Comment by danduk82** [comment]
I am still going through the tutorials, wait until I finish them to merge this PR, I might find something more.

I will rebase the PR when I am sure I have finished the tutorials and everything runs if you want.
I can also sign the `contributors.txt` meanwhile

**Comment by stevepiercy** [comment]
> I am still going through the tutorials, wait until I finish them to merge this PR, I might find something more.

Thank you for being thorough.

> I will rebase the PR when I am sure I have finished the tutorials and everything runs if you want.
> I can also sign the `contributors.txt` meanwhile

Not rebase, but a separate PR for each branch. Sorry I was not clear. Pyramid is a unique beast in that we maintain 3 active branches, `master` for development, and the 2 most recent releases, currently `1.10-branch` and `1.9-branch`. We can cherry-pick the commit from this PR and apply to both `master` and `1.9-branch`, although we usually prefer the PR be made against `master` and then do cherry-picks to backport to other branches. I hope that clarifies.

**Comment by danduk82** [comment]
ok, thanks for the clarification.

**Comment by danduk82** [comment]
@stevepiercy I think I have messed up something changing the base against which I am submitting this PR. I will close it and re-submit directly to master

**Pull request closed without merging**
