### PR TITLE
clone a new RendererHelper per request

### LINKED ISSUE #1268: Caching of RendererHelper in view_config()
*incomplete*: Wanted to get the thoughts and findings that @mmerickel were going through down in the bug tracker.

As of right now `pyramid_mako` has broken the `pyramid.reload_templates` setting, digging into it a little deeper the issue can be traced back to the renderer factories return being cached in `RendererHelper`: https://github.com/Pylons/pyramid/blob/master/pyramid/renderers.py#L400

When used with `render()`, this isn't really an issue since a new `RenderHelper` is created for each call to it.

However using `view_config()` the `RendererHelper` gets cached, so after the first request the return from the renderer factory is reified and the factory is never called again, and the `RendererHelper` persists.

---

To support `reload_templates` the returned function that deals with rendering is actually doing all of the work of verifying the template on disk has changed or not, this basically moves any logic for asset resolving out of a one time thing in the factory back into something that has to be done every time the renderer is called and there is no good way to cache the information so that asset resolving doesn't have to be done each and every call to render.

---

Is there a better way to solve this, to support `reload_templates` without having to go through the trouble the renderers currently go through? Is there a way to save the result of an asset lookup, or an effective way to cache it?

### PR DESCRIPTION
**Pull request by mmerickel**
fixes #1268

### CODE REVIEW

**Comment by bertjwregeer** [comment]
LGTM.

**Comment by mmerickel** [comment]
@mcdonc needs to sign-off since he said "don't remove the reify" without providing explanation in #1270

**Comment by mcdonc** [comment]
LGTM, no real speed concern, and I agree that caching the view renderer between calls is an optimization without much purpose.  That said, I think we should add a clone() method to the IRendererInfo interface to make it clear that it is non-optional (even though this is pretty inside baseball).

**Comment by mmerickel** [comment]
Yeah if we're worried about people using it we could easily pass a lambda/factory through the machinery but since clone was already there with a comment about its use in views, and wasn't actually called anywhere, it seemed like a good thing to use. I will add it to the interface though.

**Pull request merged**
