### PR TITLE
Change column `Page.data` to `Text` in wiki2 tutorial

### PR DESCRIPTION
**Pull request by viniciusban**
Column `data` in `Page` class is `Integer` but should be `Text` in wiki2 tutorial.

### CODE REVIEW

**Comment by mmerickel** [comment]
How'd that get through? Anyway, nice catch. LGTM

**Comment by viniciusban** [comment]
Because of this: http://www.sqlite.org/different.html

tl;dr: almost everything is stored as string. See the "Manifest typing" section.

**Comment by mmerickel** [comment]
I'm aware of sqlite's typing issues but usually SQLAlchemy will complain somewhere along the lines. In this case it looks like it just shuffles along the data from the driver however.

**Comment by viniciusban** [comment]
Indeed. :-(

**Comment by stevepiercy** [comment]
Huh, that's interesting. Using PyCharm's database browser on the database `tutorial.sqlite`, it shows `data` as type `INTEGER`. I expected `TEXT`.

I'll want to review all these docs again as I am certain there are more occurrences such as in the output of database initialization, but I'll create a new issue and do that in another PR.

**Comment by stevepiercy** [comment]
Thanks @viniciusban

**Comment by viniciusban** [comment]
Anytime, Sir.

**Pull request merged**
