### PR TITLE
fixed external link in documentation

### PR DESCRIPTION
**Pull request by bagerard**

### CODE REVIEW

**Comment by tseaver** [comment]
Thank you!

**Comment by mmerickel** [comment]
Oh boy I hope 1.3-branch actually builds on RTD now.

@bagerard Did you realize this was 1.3-branch which is unsupported? You may want to verify that the link is valid on newer versions of the pyramid docs such as 1.6-branch and master.

**Comment by tseaver** [comment]
[RTD](http://docs.pylonsproject.org/projects/pyramid/en/1.3-branch/) looks OK.  I don't know how I missed that.

**Comment by stevepiercy** [comment]
It got backported from master to 1.5, not 1.4, so I'll do that now.

1.3 builds docs, but it uses styles that got broken in Sphinx 1.3 when it changed its markup. Not worth fixing.

**Comment by bagerard** [comment]
Argh sorry for that... I accessed the doc from google and thought it was the latest version.

**Pull request merged**
