### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by anukaal**
updated classifiers

### CODE REVIEW

**Comment by mmerickel** [comment]
Thanks for the PR! To merge this we'll need to enable testing and several other pages in the docs/repo with the new version. Is that something you can help track down?

**Comment by anukaal** [comment]
> Thanks for the PR! To merge this we'll need to enable testing and several other pages in the docs/repo with the new version. Is that something you can help track down?

Yeah sure !!

**Comment by bertjwregeer** [comment]
Github actions does not yet have Python 3.10 release: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

It looks like it hasn't been released yet, so that makes sense.

**Comment by stevepiercy** [comment]
Python 3.10 is supposed to be released later today. https://twitter.com/ThePSF/status/1445010817401769985

**Comment by bertjwregeer** [comment]
I just pulled in https://github.com/Pylons/pyramid/pull/3689.

**Pull request closed without merging**
