### PR TITLE
Explicitly declare the PickleSerializer()

### PR DESCRIPTION
**Pull request by joulez**
The default currently for SignedCookieSessionFactory is the PickleSerializer. If this was to ever change tests will fail.
Looking forwardly to a JSONSerializer and related tests in a seperate PR but interested in any comments. Thanks.

### CODE REVIEW

**Comment by tseaver** [comment]
I don't really see the point:  the Travis failure is in coverage for the following test in `SignedCookieSesstionFactory.__init__`:

     if serializer is None:
        serializer = PickleSerializer()

Now, if the PR changed the signature of `_makeOne` to take an optional `serializer` (defaulting to `None`) and pass it through to the class, I could at least see how it might be useful in the cases you are contemplating.

**Comment by joulez** [comment]
Pickle serialization is the default method in pyramid and alot of tests are orientated around this (re `_serialize`. I suppose I'm wondering if it would be a good idea to be more explicit about what serialization methods are being used in the tests. 

If at any point in the future the serializer defaults to something else other than `PickleSerializer` a couple of these tests (that call `_serialize`) fail and/or if pyramid wishes to support and include other serializers (ie. `JSONSerializer`).

**Comment by tseaver** [comment]
Sure, some tests would fail if the default changed:  that is an expected thing.  As I said, if you wanted to change `_makeOne` to allow passing a non-default seraiizer, that would be fine.  I just don't see the point in duplicating the hard-wiring of the default from the code itself into a test jig.

**Comment by joulez** [comment]
Thanks for the clarity. I think I approached this from the wrong direction. Please review #1525 and perhaps a discussion on changing the default serializer (and refactoring tests for it) can be had another time. There is concern that pickle can be volatile and insecure. But a least a alternative serializer can be provided perhaps?

**Comment by bertjwregeer** [comment]
@joulez An alternate serializer is available in `WebOb` and may be used if you wish, however we can't change it wholesale due to the contract of `ISession`.

**Pull request closed without merging**
