### PR TITLE
Fix tests on Windows

### PR DESCRIPTION
**Pull request by Cito**
Two tests do not pass under Windows where backslashes instead of slashes are used in file paths. This fix makes the tests platform independent.

### CODE REVIEW

**Comment by Cito** [comment]
Actually wanted to push a fix for the issue with int ports in session.py but it was already fixed :+1:

**Comment by mmerickel** [comment]
Thanks, I need to look into configuring appveyor to get our test suite running on windows. This will serve as a good reminder.

**Comment by mmerickel** [comment]
Cool, I got appveyor setup and tests pass. Thank you!

**Comment by Cito** [comment]
:+1:

**Pull request merged**
