### PR TITLE
Ripping daemonization out of pserve

### PR DESCRIPTION
**Pull request by zrayn**

### CODE REVIEW

**Comment by bertjwregeer** [comment]
Awesome!

**Comment by mmerickel** [comment]
This looks great! Can you also pull out the user/group code from `change_user_group`?

**Comment by zrayn** [comment]
done

**Comment by mcdonc** [comment]
Woot.  LGTM.  Could you add a note to CHANGES.txt about the impact of this feature?  Something that describes each of the command-line options that were removed, and a general suggestion to use a "real" process manager again?

**Comment by mcdonc** [comment]
Also, if you haven't already done so, @zrayne, can you add your name to CONTRIBUTORS.txt?

**Comment by mcdonc** [comment]
Great.

I think if you merge master back to your branch, we'd be ready to merge this.

**Comment by zrayn** [comment]
CHANGES updated and merge conflicts resolved

**Pull request merged**
