### PR TITLE
Update tutorial_approach.rst

### PR DESCRIPTION
**Pull request by areski**
fix link to pyramid_tutorials repo

### CODE REVIEW

**Comment by stevepiercy** [comment]
@areski Incorrect. The steps are in the same repo:
http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/index.html#contents
https://github.com/Pylons/pyramid/tree/1.5-branch/docs/quick_tutorial

The pyramid_tutorials may be out of date and out of sync with the official docs. In fact, @pauleveritt should [pyramid_tutorials/getting_started](https://github.com/Pylons/pyramid_tutorials/tree/master/getting_started) be removed/refer to the official docs? I think it is confusing.

**Comment by areski** [comment]
thank!
why not having a link to https://github.com/Pylons/pyramid/tree/1.5-branch/docs/quick_tutorial then?

**Comment by stevepiercy** [comment]
@areski It would take the user out of the [HTML presentation](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/index.html) of the tutorial. That would be utterly confusing to the user.

**Comment by areski** [comment]
Ok, I guess I got confused by the wording "The steps each correspond to a directory in this repo" where I was expecting to see some git repo.
Thanks for the help

**Pull request closed without merging**
